# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

pod 'SDWebImage', '~>3.7.2'
target 'Wechat' do

end

target 'WechatTests' do

end

target 'WechatUITests' do

end

